//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.17 at 02:51:19 PM IST 
//


package cdot.ccsp.utils;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import cdot.onem2m.resource.xsd.ChildResourceRef;
import cdot.onem2m.resource.xsd.FlexContainerResource;
import cdot.onem2m.resource.xsd.Subscription;


/**
 * <p>Java class for bioElectricalImpedanceAnalysis complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bioElectricalImpedanceAnalysis">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}flexContainerResource">
 *       &lt;sequence>
 *         &lt;element name="water" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="fat" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="muscle" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="bone" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="visceraFat" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="kcal" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="resistance" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="childResource" type="{http://www.onem2m.org/xml/protocols}childResourceRef" maxOccurs="unbounded"/>
 *           &lt;choice maxOccurs="unbounded">
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}subscription"/>
 *           &lt;/choice>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bioElectricalImpedanceAnalysis", propOrder = {
    "water",
    "fat",
    "muscle",
    "bone",
    "visceraFat",
    "kcal",
    "resistance",
    "childResource",
    "subscription"
})
public class BioElectricalImpedanceAnalysis
    extends FlexContainerResource
{

    protected float water;
    protected float fat;
    protected float muscle;
    protected float bone;
    protected float visceraFat;
    protected float kcal;
    protected boolean resistance;
    protected List<ChildResourceRef> childResource;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected List<Subscription> subscription;

    /**
     * Gets the value of the water property.
     * 
     */
    public float getWater() {
        return water;
    }

    /**
     * Sets the value of the water property.
     * 
     */
    public void setWater(float value) {
        this.water = value;
    }

    /**
     * Gets the value of the fat property.
     * 
     */
    public float getFat() {
        return fat;
    }

    /**
     * Sets the value of the fat property.
     * 
     */
    public void setFat(float value) {
        this.fat = value;
    }

    /**
     * Gets the value of the muscle property.
     * 
     */
    public float getMuscle() {
        return muscle;
    }

    /**
     * Sets the value of the muscle property.
     * 
     */
    public void setMuscle(float value) {
        this.muscle = value;
    }

    /**
     * Gets the value of the bone property.
     * 
     */
    public float getBone() {
        return bone;
    }

    /**
     * Sets the value of the bone property.
     * 
     */
    public void setBone(float value) {
        this.bone = value;
    }

    /**
     * Gets the value of the visceraFat property.
     * 
     */
    public float getVisceraFat() {
        return visceraFat;
    }

    /**
     * Sets the value of the visceraFat property.
     * 
     */
    public void setVisceraFat(float value) {
        this.visceraFat = value;
    }

    /**
     * Gets the value of the kcal property.
     * 
     */
    public float getKcal() {
        return kcal;
    }

    /**
     * Sets the value of the kcal property.
     * 
     */
    public void setKcal(float value) {
        this.kcal = value;
    }

    /**
     * Gets the value of the resistance property.
     * 
     */
    public boolean isResistance() {
        return resistance;
    }

    /**
     * Sets the value of the resistance property.
     * 
     */
    public void setResistance(boolean value) {
        this.resistance = value;
    }

    /**
     * Gets the value of the childResource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the childResource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChildResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChildResourceRef }
     * 
     * 
     */
    public List<ChildResourceRef> getChildResource() {
        if (childResource == null) {
            childResource = new ArrayList<ChildResourceRef>();
        }
        return this.childResource;
    }

    /**
     * Gets the value of the subscription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subscription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubscription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Subscription }
     * 
     * 
     */
    public List<Subscription> getSubscription() {
        if (subscription == null) {
            subscription = new ArrayList<Subscription>();
        }
        return this.subscription;
    }

}
