//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.17 at 02:51:19 PM IST 
//


package cdot.ccsp.utils;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;

import cdot.onem2m.resource.xsd.AnnouncedFlexContainerResource;
import cdot.onem2m.resource.xsd.ChildResourceRef;
import cdot.onem2m.resource.xsd.Subscription;


/**
 * <p>Java class for deviceKettleAnnc complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="deviceKettleAnnc">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}announcedFlexContainerResource">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="childResource" type="{http://www.onem2m.org/xml/protocols}childResourceRef" maxOccurs="unbounded"/>
 *           &lt;choice maxOccurs="unbounded">
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}faultDetection"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}faultDetectionAnnc"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}runState"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}runStateAnnc"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}waterStatus"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}waterStatusAnnc"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}boilingSwitch"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}boilingSwitchAnnc"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}temperature"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}temperatureAnnc"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}keepWarm"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}keepWarmAnnc"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}subscription"/>
 *           &lt;/choice>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deviceKettleAnnc", propOrder = {
    "childResource",
    "faultDetectionOrFaultDetectionAnncOrRunState"
})
public class DeviceKettleAnnc
    extends AnnouncedFlexContainerResource
{

    protected List<ChildResourceRef> childResource;
    @XmlElements({
        @XmlElement(name = "faultDetection", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = FaultDetection.class),
        @XmlElement(name = "faultDetectionAnnc", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = FaultDetectionAnnc.class),
        @XmlElement(name = "runState", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = RunState.class),
        @XmlElement(name = "runStateAnnc", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = RunStateAnnc.class),
        @XmlElement(name = "waterStatus", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = LiquidRemaining.class),
        @XmlElement(name = "waterStatusAnnc", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = LiquidRemainingAnnc.class),
        @XmlElement(name = "boilingSwitch", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = BinarySwitch.class),
        @XmlElement(name = "boilingSwitchAnnc", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = BinarySwitchAnnc.class),
        @XmlElement(name = "temperature", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = Temperature.class),
        @XmlElement(name = "temperatureAnnc", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = TemperatureAnnc.class),
        @XmlElement(name = "keepWarm", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = KeepWarm.class),
        @XmlElement(name = "keepWarmAnnc", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = KeepWarmAnnc.class),
        @XmlElement(name = "subscription", namespace = "http://www.onem2m.org/xml/protocols", type = Subscription.class)
    })
    protected List<Object> faultDetectionOrFaultDetectionAnncOrRunState;

    /**
     * Gets the value of the childResource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the childResource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChildResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChildResourceRef }
     * 
     * 
     */
    public List<ChildResourceRef> getChildResource() {
        if (childResource == null) {
            childResource = new ArrayList<ChildResourceRef>();
        }
        return this.childResource;
    }

    /**
     * Gets the value of the faultDetectionOrFaultDetectionAnncOrRunState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the faultDetectionOrFaultDetectionAnncOrRunState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFaultDetectionOrFaultDetectionAnncOrRunState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FaultDetection }
     * {@link FaultDetectionAnnc }
     * {@link RunState }
     * {@link RunStateAnnc }
     * {@link LiquidRemaining }
     * {@link LiquidRemainingAnnc }
     * {@link BinarySwitch }
     * {@link BinarySwitchAnnc }
     * {@link Temperature }
     * {@link TemperatureAnnc }
     * {@link KeepWarm }
     * {@link KeepWarmAnnc }
     * {@link Subscription }
     * 
     * 
     */
    public List<Object> getFaultDetectionOrFaultDetectionAnncOrRunState() {
        if (faultDetectionOrFaultDetectionAnncOrRunState == null) {
            faultDetectionOrFaultDetectionAnncOrRunState = new ArrayList<Object>();
        }
        return this.faultDetectionOrFaultDetectionAnncOrRunState;
    }

}
