//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.17 at 02:51:19 PM IST 
//


package cdot.ccsp.utils;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;

import cdot.onem2m.resource.xsd.ChildResourceRef;
import cdot.onem2m.resource.xsd.FlexContainerResource;
import cdot.onem2m.resource.xsd.Subscription;


/**
 * <p>Java class for deviceAirConditioner complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="deviceAirConditioner">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}flexContainerResource">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="childResource" type="{http://www.onem2m.org/xml/protocols}childResourceRef" maxOccurs="unbounded"/>
 *           &lt;choice maxOccurs="unbounded">
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}binarySwitch"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}runState"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}airConJobMode"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}airConOperationMode"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}airCleanOperationMode"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}temperature"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}timer"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}sleepTimer"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}turbo"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}airFlow"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}powerSave"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}airQualitySensor"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}filterInfo"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}subscription"/>
 *           &lt;/choice>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deviceAirConditioner", propOrder = {
    "childResource",
    "binarySwitchOrRunStateOrAirConJobMode"
})
public class DeviceAirConditioner
    extends FlexContainerResource
{

    protected List<ChildResourceRef> childResource;
    @XmlElementRefs({
        @XmlElementRef(name = "airConOperationMode", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "binarySwitch", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "airFlow", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "filterInfo", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "runState", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "temperature", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "airQualitySensor", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "airConJobMode", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "timer", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "airCleanOperationMode", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "turbo", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "powerSave", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "sleepTimer", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "subscription", namespace = "http://www.onem2m.org/xml/protocols", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> binarySwitchOrRunStateOrAirConJobMode;

    /**
     * Gets the value of the childResource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the childResource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChildResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChildResourceRef }
     * 
     * 
     */
    public List<ChildResourceRef> getChildResource() {
        if (childResource == null) {
            childResource = new ArrayList<ChildResourceRef>();
        }
        return this.childResource;
    }

    /**
     * Gets the value of the binarySwitchOrRunStateOrAirConJobMode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the binarySwitchOrRunStateOrAirConJobMode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBinarySwitchOrRunStateOrAirConJobMode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link OperationMode }{@code >}
     * {@link JAXBElement }{@code <}{@link BinarySwitch }{@code >}
     * {@link JAXBElement }{@code <}{@link AirFlow }{@code >}
     * {@link JAXBElement }{@code <}{@link FilterInfo }{@code >}
     * {@link JAXBElement }{@code <}{@link RunState }{@code >}
     * {@link JAXBElement }{@code <}{@link Temperature }{@code >}
     * {@link JAXBElement }{@code <}{@link AirQualitySensor }{@code >}
     * {@link JAXBElement }{@code <}{@link AirConJobMode }{@code >}
     * {@link JAXBElement }{@code <}{@link Timer }{@code >}
     * {@link JAXBElement }{@code <}{@link OperationMode }{@code >}
     * {@link JAXBElement }{@code <}{@link Turbo }{@code >}
     * {@link JAXBElement }{@code <}{@link PowerSave }{@code >}
     * {@link JAXBElement }{@code <}{@link Timer }{@code >}
     * {@link JAXBElement }{@code <}{@link Subscription }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getBinarySwitchOrRunStateOrAirConJobMode() {
        if (binarySwitchOrRunStateOrAirConJobMode == null) {
            binarySwitchOrRunStateOrAirConJobMode = new ArrayList<JAXBElement<?>>();
        }
        return this.binarySwitchOrRunStateOrAirConJobMode;
    }

}
