//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.17 at 02:51:19 PM IST 
//


package cdot.ccsp.utils;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import cdot.onem2m.resource.xsd.ChildResourceRef;
import cdot.onem2m.resource.xsd.FlexContainerResource;
import cdot.onem2m.resource.xsd.Subscription;


/**
 * <p>Java class for glucometer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="glucometer">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}flexContainerResource">
 *       &lt;sequence>
 *         &lt;element name="concentration" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="hba1c" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="contextExercise" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="contextMedication" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="contextCarbohydratesAmount" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="contextCarbohydratesSource" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contextMeal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contextLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contextTester" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contextHealth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="childResource" type="{http://www.onem2m.org/xml/protocols}childResourceRef" maxOccurs="unbounded"/>
 *           &lt;choice maxOccurs="unbounded">
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}subscription"/>
 *           &lt;/choice>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "glucometer", propOrder = {
    "concentration",
    "hba1C",
    "contextExercise",
    "contextMedication",
    "contextCarbohydratesAmount",
    "contextCarbohydratesSource",
    "contextMeal",
    "contextLocation",
    "contextTester",
    "contextHealth",
    "childResource",
    "subscription"
})
public class Glucometer
    extends FlexContainerResource
{

    protected float concentration;
    @XmlElement(name = "hba1c")
    protected Float hba1C;
    protected Float contextExercise;
    protected Float contextMedication;
    protected Float contextCarbohydratesAmount;
    protected String contextCarbohydratesSource;
    protected String contextMeal;
    protected String contextLocation;
    protected String contextTester;
    protected String contextHealth;
    protected List<ChildResourceRef> childResource;
    @XmlElement(namespace = "http://www.onem2m.org/xml/protocols")
    protected List<Subscription> subscription;

    /**
     * Gets the value of the concentration property.
     * 
     */
    public float getConcentration() {
        return concentration;
    }

    /**
     * Sets the value of the concentration property.
     * 
     */
    public void setConcentration(float value) {
        this.concentration = value;
    }

    /**
     * Gets the value of the hba1C property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getHba1C() {
        return hba1C;
    }

    /**
     * Sets the value of the hba1C property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setHba1C(Float value) {
        this.hba1C = value;
    }

    /**
     * Gets the value of the contextExercise property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getContextExercise() {
        return contextExercise;
    }

    /**
     * Sets the value of the contextExercise property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setContextExercise(Float value) {
        this.contextExercise = value;
    }

    /**
     * Gets the value of the contextMedication property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getContextMedication() {
        return contextMedication;
    }

    /**
     * Sets the value of the contextMedication property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setContextMedication(Float value) {
        this.contextMedication = value;
    }

    /**
     * Gets the value of the contextCarbohydratesAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getContextCarbohydratesAmount() {
        return contextCarbohydratesAmount;
    }

    /**
     * Sets the value of the contextCarbohydratesAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setContextCarbohydratesAmount(Float value) {
        this.contextCarbohydratesAmount = value;
    }

    /**
     * Gets the value of the contextCarbohydratesSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContextCarbohydratesSource() {
        return contextCarbohydratesSource;
    }

    /**
     * Sets the value of the contextCarbohydratesSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContextCarbohydratesSource(String value) {
        this.contextCarbohydratesSource = value;
    }

    /**
     * Gets the value of the contextMeal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContextMeal() {
        return contextMeal;
    }

    /**
     * Sets the value of the contextMeal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContextMeal(String value) {
        this.contextMeal = value;
    }

    /**
     * Gets the value of the contextLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContextLocation() {
        return contextLocation;
    }

    /**
     * Sets the value of the contextLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContextLocation(String value) {
        this.contextLocation = value;
    }

    /**
     * Gets the value of the contextTester property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContextTester() {
        return contextTester;
    }

    /**
     * Sets the value of the contextTester property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContextTester(String value) {
        this.contextTester = value;
    }

    /**
     * Gets the value of the contextHealth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContextHealth() {
        return contextHealth;
    }

    /**
     * Sets the value of the contextHealth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContextHealth(String value) {
        this.contextHealth = value;
    }

    /**
     * Gets the value of the childResource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the childResource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChildResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChildResourceRef }
     * 
     * 
     */
    public List<ChildResourceRef> getChildResource() {
        if (childResource == null) {
            childResource = new ArrayList<ChildResourceRef>();
        }
        return this.childResource;
    }

    /**
     * Gets the value of the subscription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subscription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubscription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Subscription }
     * 
     * 
     */
    public List<Subscription> getSubscription() {
        if (subscription == null) {
            subscription = new ArrayList<Subscription>();
        }
        return this.subscription;
    }

}
