//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.17 at 02:51:19 PM IST 
//


package cdot.ccsp.utils;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;

import cdot.onem2m.resource.xsd.AnnouncedFlexContainerResource;
import cdot.onem2m.resource.xsd.ChildResourceRef;
import cdot.onem2m.resource.xsd.Subscription;


/**
 * <p>Java class for timerAnnc complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="timerAnnc">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}announcedFlexContainerResource">
 *       &lt;sequence>
 *         &lt;element name="referenceTimer" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="targetTimeToStart" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="targetTimeToStop" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="estimatedTimeToEnd" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="runningTime" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="targetDuration" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="absoluteStartTime" type="{http://www.onem2m.org/xml/protocols}timestamp" minOccurs="0"/>
 *         &lt;element name="absoluteStopTime" type="{http://www.onem2m.org/xml/protocols}timestamp" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="childResource" type="{http://www.onem2m.org/xml/protocols}childResourceRef" maxOccurs="unbounded"/>
 *           &lt;choice maxOccurs="unbounded">
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}activateClockTimer"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols/homedomain}deactivateClockTimer"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}subscription"/>
 *           &lt;/choice>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "timerAnnc", propOrder = {
    "referenceTimer",
    "targetTimeToStart",
    "targetTimeToStop",
    "estimatedTimeToEnd",
    "runningTime",
    "targetDuration",
    "absoluteStartTime",
    "absoluteStopTime",
    "childResource",
    "activateClockTimerOrDeactivateClockTimerOrSubscription"
})
public class TimerAnnc
    extends AnnouncedFlexContainerResource
{

    protected BigInteger referenceTimer;
    protected BigInteger targetTimeToStart;
    protected BigInteger targetTimeToStop;
    protected BigInteger estimatedTimeToEnd;
    protected BigInteger runningTime;
    protected BigInteger targetDuration;
    protected String absoluteStartTime;
    protected String absoluteStopTime;
    protected List<ChildResourceRef> childResource;
    @XmlElements({
        @XmlElement(name = "activateClockTimer", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = ActivateClockTimer.class),
        @XmlElement(name = "deactivateClockTimer", namespace = "http://www.onem2m.org/xml/protocols/homedomain", type = DeactivateClockTimer.class),
        @XmlElement(name = "subscription", namespace = "http://www.onem2m.org/xml/protocols", type = Subscription.class)
    })
    protected List<Object> activateClockTimerOrDeactivateClockTimerOrSubscription;

    /**
     * Gets the value of the referenceTimer property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReferenceTimer() {
        return referenceTimer;
    }

    /**
     * Sets the value of the referenceTimer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReferenceTimer(BigInteger value) {
        this.referenceTimer = value;
    }

    /**
     * Gets the value of the targetTimeToStart property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTargetTimeToStart() {
        return targetTimeToStart;
    }

    /**
     * Sets the value of the targetTimeToStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTargetTimeToStart(BigInteger value) {
        this.targetTimeToStart = value;
    }

    /**
     * Gets the value of the targetTimeToStop property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTargetTimeToStop() {
        return targetTimeToStop;
    }

    /**
     * Sets the value of the targetTimeToStop property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTargetTimeToStop(BigInteger value) {
        this.targetTimeToStop = value;
    }

    /**
     * Gets the value of the estimatedTimeToEnd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEstimatedTimeToEnd() {
        return estimatedTimeToEnd;
    }

    /**
     * Sets the value of the estimatedTimeToEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEstimatedTimeToEnd(BigInteger value) {
        this.estimatedTimeToEnd = value;
    }

    /**
     * Gets the value of the runningTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRunningTime() {
        return runningTime;
    }

    /**
     * Sets the value of the runningTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRunningTime(BigInteger value) {
        this.runningTime = value;
    }

    /**
     * Gets the value of the targetDuration property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTargetDuration() {
        return targetDuration;
    }

    /**
     * Sets the value of the targetDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTargetDuration(BigInteger value) {
        this.targetDuration = value;
    }

    /**
     * Gets the value of the absoluteStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbsoluteStartTime() {
        return absoluteStartTime;
    }

    /**
     * Sets the value of the absoluteStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbsoluteStartTime(String value) {
        this.absoluteStartTime = value;
    }

    /**
     * Gets the value of the absoluteStopTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbsoluteStopTime() {
        return absoluteStopTime;
    }

    /**
     * Sets the value of the absoluteStopTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbsoluteStopTime(String value) {
        this.absoluteStopTime = value;
    }

    /**
     * Gets the value of the childResource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the childResource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChildResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChildResourceRef }
     * 
     * 
     */
    public List<ChildResourceRef> getChildResource() {
        if (childResource == null) {
            childResource = new ArrayList<ChildResourceRef>();
        }
        return this.childResource;
    }

    /**
     * Gets the value of the activateClockTimerOrDeactivateClockTimerOrSubscription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activateClockTimerOrDeactivateClockTimerOrSubscription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActivateClockTimerOrDeactivateClockTimerOrSubscription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActivateClockTimer }
     * {@link DeactivateClockTimer }
     * {@link Subscription }
     * 
     * 
     */
    public List<Object> getActivateClockTimerOrDeactivateClockTimerOrSubscription() {
        if (activateClockTimerOrDeactivateClockTimerOrSubscription == null) {
            activateClockTimerOrDeactivateClockTimerOrSubscription = new ArrayList<Object>();
        }
        return this.activateClockTimerOrDeactivateClockTimerOrSubscription;
    }

}
